---

- hosts: all

  tasks:
    - name: install packages
      apt:
        pkg:
          - screen
          - lshw
          - alpine
          - neofetch
          - inxi
        state: present
  
  roles:
    - unattended_upgrades
    - install_vim

- hosts: calibre
  roles:
    - calibre-server

- hosts: scanner
  roles:
    - remote_scanner
