---

- name: install required packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - lm-sensors
      - fancontrol

- name: configure fan speeds
  blockinfile:
    path: /boot/config.txt
    insertafter: EOF
    marker: "# {mark} Ansible Managed Block - PoE Hat Fan Speed"
    block: |
      dtparam=poe_fan_temp0=50000
      dtparam=poe_fan_temp1=60000
      dtparam=poe_fan_temp2=70000
      dtparam=poe_fan_temp3=80000

